### ISSUE TITLE
Justify ignored exception

### ISSUE THREAD

**Issue by rnavarropiris** [slub/urnlib#11]
An exception is silently catched without explanation: [source](https://github.com/slub/urnlib/blob/2fe8b5717f760ab906b30f1cf2cde84a32cb391f/src/main/java/de/slub/urn/NamespaceSpecificString.java#L156)

My guess is the exception "cannot happen", but a brief explanation (in the form of an in-line comment) would be nice :)

**Comment by claussni** [comment]
StringReader read() throws IOException only if StringReader has been initialized with null. In the context of this method, this currently never happens. It would be a "programmer error" that could happen after an invalid refactoring, misusing the private method.

I would suggest throwing a RuntimeException (e.g. IllegalArgumentException) instead of just swallowing the exception. What do you think?

**Comment by rnavarropiris** [comment]
Sounds like a great solution :)
