### ISSUE TITLE
RQF_RFC8141.initialToString() concat q and r component without `&`

### ISSUE THREAD

**Issue by floriangasc** [slub/urnlib#25]
Hello, 

I wonder if it's normal that de.slub.urn.RQF_RFC8141.initialToString() concat q and r component without `&` ?

 If it's not, do you like a p.r ? 

Thanks in advance.

**Comment by claussni** [comment]
Hi @floriangasc ,
sorry for replying so late. I wasn't notified of you request.
I will have a look at the issue and get back to you.
Regards, Ralf

**Comment by floriangasc** [comment]
Hi @claussni 

No problem. I have made a beginning of p.r https://github.com/slub/urnlib/pull/26

**Comment by claussni** [comment]
Hey @floriangasc,

I took a brief look at the code and RFC 8141 and it seems that this might be an actual bug since the the RQF components parser actually considers the `&`. So if you could provide a test and a fix in #26, that would be great!

Another request: Please keep formatting changes down to a minimum. It's alright if you reformat the methods you changed. But everything unrelated should be kept as is. 

Thank you!

**Comment by floriangasc** [comment]
Hi @claussni 

Awesome! I will write tests soon and keep, at the maximum, the existing formatting.

**Comment by floriangasc** [comment]
Hi @claussni 

I finally took the time ! Sorry for the delay. I write 2 test and fix/restore indentation. 

Let me known if you want, I change something.
